version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print Hello"
          command: "echo Hello!"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print World"
          command: "echo World!"

workflows:
  welcome:
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires: [print_hello]
