version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print Hello"
          command: "echo Hello!"

  save_helloworld:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Save HelloWorld To File"
          command: echo "HelloWorld" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_outputfile:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "Print File Content to console"
          command: cat output.txt

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR

workflows:
  dev-build:
    jobs:
      - welcome/run
      - print_hello
      - save_helloworld
      - print_outputfile:
          requires: [save_helloworld]
      - build
